global:
  ## Override the deployment namespace
  namespaceOverride: logging

#hostNetwork and dnsPolicy are critical for enabling large clusters to avoid making calls to API server
# see this link https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#optional-feature-using-kubelet-to-get-metadata
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

# NOTE: extraFilters config for using Kubelet to get the Metadata instead of talking to API server for large clusters
filter:
  name: "kubernetes"
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "log_processed"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "Off"
  bufferSize: "0"
  extraFilters: |
    Kube_Tag_Prefix     application.var.log.containers.
    Labels              Off
    Annotations         Off
    Use_Kubelet         true
    Kubelet_Port        10250
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token

cloudWatch:
  enabled: true
  match: "*"
  region: ${region}
  logGroupName: ${aws_for_fluent_bit_cw_log}
  logStreamName:
  logStreamPrefix: "fluentbit-"
  logKey:
  logFormat:
  roleArn:
  autoCreateGroup: true
  endpoint:
  credentialsEndpoint:  {}

firehose:
  enabled: false

kinesis:
  enabled: false

elasticsearch:
  enabled: false

# Use this config to write logs to an S3 bucket.
# Pre-req
#  1/ S3 bucket for logging
#  2/ Additional IAM policy for FluentBit add-on IRSA config
#  3/ Add this to Terraform to pass additional IAM policy "aws_for_fluentbit_irsa_policies = ["<ENTER_NEW_IAM_POLICY_FOR_S3>"]"

additionalOutputs: |
  [OUTPUT]
      Name                            s3
      Match                           *
      region                          ${region}
      bucket                          ${s3_bucket_name}
      total_file_size                 100M
      s3_key_format                   /fluentbit-logs/$TAG[4]/year=%Y/month=%m/day=%d/hour=%H/
      s3_key_format_tag_delimiters    ._
      store_dir                       /home/ec2-user/buffer
      upload_timeout                  10m

serviceAccount:
  create: true

# Resource config for large clusters
resources:
  limits:
    cpu: 1000m
    memory: 1500Mi
  requests:
    cpu: 500m
    memory: 500Mi

## Assign a PriorityClassName to pods if set
priorityClassName: system-node-critical

updateStrategy:
  type: RollingUpdate

nodeSelector:
  kubernetes.io/os: linux
