server:
  retention: 1h
  remoteWrite:
    - queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  verticalAutoscaler:
    enabled: true
    updateMode: "Auto"
    containerPolicies:
      - containerName: "prometheus-server"
        minAllowed:
          cpu: 500m
          memory: 1Gi
        maxAllowed:
          cpu: 1000m
          memory: 4Gi

  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core
  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 20Gi
    storageClass: gp2

alertmanager:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

pushgateway:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

nodeExporter:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

# Additional scrape config for KubeCost
extraScrapeConfigs: |
  - job_name: kubecost
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names:
          - kubecost-cost-analyzer.kubecost.svc
        type: 'A'
        port: 9003
