server:
  retention: 1h
  remoteWrite:
    - queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s
    external_labels:
      cluster_id: ${eks_cluster_id}  # Each cluster should have a unique ID

  # This is required to upgrade the Prometheus version. Avoids the db lock error
  strategy:
    type: Recreate

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  verticalAutoscaler:
    enabled: true
    updateMode: "Auto"
    containerPolicies:
      - containerName: "prometheus-server"
        minAllowed:
          cpu: 500m
          memory: 1Gi
        maxAllowed:
          cpu: 1000m
          memory: 4Gi

  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 80Gi
    storageClass: gp2
  extraArgs:
    query.max-concurrency: 1
    query.max-samples: 100000000

alertmanager:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

pushgateway:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: core

nodeExporter:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

# Additional scrape config for Apache YuniKorn Scheduler metrics
extraScrapeConfigs: |
  - job_name: 'yunikorn'
    scrape_interval: 1s
    metrics_path: '/ws/v1/metrics'
    static_configs:
      - targets:
          - yunikorn-service.yunikorn.svc.cluster.local:9080
